name: 定时获取数据

on:
  schedule:
    - cron: '0 2 * * *'  # 每12小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  fetch-and-process:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 添加写入权限
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整的git历史
      
      - name: 切换分支
        run: |
          git fetch origin # 获取远程更新
          git reset --hard origin/main  # 将本地 main 分支重置为远程 main 分支
          git clean -fd
          
      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: 安装依赖
        run: npm install axios
        
          
      - name: 运行数据处理脚本
        run: node process-data.js
        
      - name: 提交更改
        run: |          
          # 确保主分支存在
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          git add data.m3u
          git commit -m "更新数据文件" || exit 0
          git push --set-upstream origin main 
